"""Stock의 price 칼럼 데이터 타입 변경

Revision ID: 148c819b5489
Revises: 8d4a7ee5996e
Create Date: 2025-03-08 14:03:38.737320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "148c819b5489"
down_revision: Union[str, None] = "8d4a7ee5996e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock",
        "price",
        existing_type=sa.NUMERIC(precision=13, scale=4),
        type_=sa.Float(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock",
        "price",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=13, scale=4),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
