"""BacktestResult의 data_id 타입 변경

Revision ID: 751a453883b1
Revises: 9c0a545bdee5
Create Date: 2025-03-09 23:14:07.305009

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "751a453883b1"
down_revision: Union[str, None] = "9c0a545bdee5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backtest_results",
        "data_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backtest_results",
        "data_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
