"""BacktestResult 모델 추가

Revision ID: cb26f511f0d3
Revises: 148c819b5489
Create Date: 2025-03-09 14:56:34.050572

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb26f511f0d3"
down_revision: Union[str, None] = "148c819b5489"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_results",
        sa.Column("data_id", sa.String(), nullable=False),
        sa.Column("start_year", sa.Integer(), nullable=False),
        sa.Column("start_month", sa.Integer(), nullable=False),
        sa.Column("initial_investment", sa.Float(), nullable=False),
        sa.Column("trade_date", sa.Integer(), nullable=False),
        sa.Column("trading_fee", sa.Float(), nullable=False),
        sa.Column("rebalance_period", sa.Integer(), nullable=False),
        sa.Column("nav_history", sa.JSON(), nullable=False),
        sa.Column("rebalance_weights", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("data_id"),
    )
    op.create_index(
        op.f("ix_backtest_results_data_id"),
        "backtest_results",
        ["data_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_backtest_results_data_id"), table_name="backtest_results")
    op.drop_table("backtest_results")
    # ### end Alembic commands ###
